project/board/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.list_of_board, name='list_of_board'),
    url(r'^(?P<slug>[-\w]+)/(?P<board_id>[0-9]+)/$', views.board_detail, name='board_detail'),
    url(r'^table/create/$', views.create_board, name='create_board'),
    url(r'^table/card/create/$', views.create_card, name='create_card'),
    url(r'^(?P<slug>[-\w]+)/(?P<board_id>[0-9]+)/delete_board/$', views.delete_board, name='delete_board'),
    url(r'^(?P<slug>[-\w]+)/(?P<board_id>[0-9]+)/delete_card/(?P<card_id>[0-9]+)/$', views.delete_card, name='delete_card'),
    url(r'^(?P<slug>[-\w]+)/(?P<board_id>[0-9]+)/update_card_success/(?P<card_id>[0-9]+)/$', views.success_button, name='success_button'),
    url(r'^(?P<slug>[-\w]+)/(?P<board_id>[0-9]+)/update_card_warning/(?P<card_id>[0-9]+)/$', views.warning_button, name='warning_button'),
    url(r'^(?P<slug>[-\w]+)/(?P<board_id>[0-9]+)/update_card_danger/(?P<card_id>[0-9]+)/$', views.danger_button, name='danger_button'),
]

project/index/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

project/project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('index.urls')),
    url(r'^board/', include('board.urls', namespace='board')),
]

project/board/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.timezone import now


class Board(models.Model):
    title = models.CharField(max_length=15, unique=True)
    description = models.CharField(max_length=25)
    category = models.CharField(max_length=20)
    slug = models.SlugField(max_length=15)
    created_at = models.DateField(auto_now_add=True)
    created_at_time = models.TimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('board:board_detail', kwargs={'slug': self.slug, 'board_id': self.pk})

    def __str__(self):
        return self.title


class Card(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    title_card = models.CharField(max_length=15)
    description_card = models.CharField(max_length=15)
    colors = models.CharField(max_length=20, blank=True)

    def __str__(self):
        return self.title_card

project/index/models.py
from django.db import models

# Create your models here.

project/board/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponse, HttpResponseRedirect
from .models import Board, Card
from django.utils.text import slugify


def list_of_board(request):
    """Return list of created and stored boards by user."""
    board = Board.objects.all()
    template = 'board/board.html'
    context = {'board': board}
    return render(request, template, context)


def board_detail(request, slug, board_id):
    """Return detail of specific board, shows assigned cards."""
    board = Board.objects.get(slug=slug, pk=board_id)
    context = {'board': board}
    template = 'board/board_detail.html'
    return render(request, template, context)


def create_board(request):
    """Receive data send by form.js script.
    Client side form validation is too weak, someone can use tool like POSTMAN,
    and send request with POST method with incorrect data to DB."""
    if request.method == 'POST':
        slug = request.POST['title']
        good_slug = slugify(slug)
        title = request.POST['title']
        good_title = " ".join(title.split())
        description = request.POST['description'].strip()
        category = request.POST['category'].strip()
        if title.isspace() or description.isspace() or category.isspace():
            return HttpResponse(status=405)
        else:
            if (len(good_title) >= 5 and len(description) >= 5 and len(category) >= 5 and len(good_slug) > 0) and \
                    (len(good_title) <= 15 and len(description) <= 25 and len(category) <= 25):
                obj, created = Board.objects.get_or_create(title=good_title,
                                                           defaults=
                                                           {'description': description,
                                                            'category': category,
                                                            'slug': good_slug})
                if created:
                    return HttpResponse(status=200)
                else:
                    return HttpResponse(status=406)
            else:
                return HttpResponse(status=409)
    else:
        return HttpResponse(status=400)


def create_card(request):
    """Receive data send by form_cards.js script.
    Client side form validation is too weak, someone can use tool like POSTMAN,
    and send request with POST method with incorrect data to DB."""
    if request.method == 'POST':
        title_board = request.POST['board_name']
        title_card = request.POST['title_card']
        good_title_card = " ".join(title_card.split())
        description_card = request.POST['description_card'].strip()
        unique_board = Board.objects.get(title=title_board)
        if title_card.isspace() or description_card.isspace():
            return HttpResponse(status=405)
        else:
            if (len(good_title_card) >= 5 and len(description_card) >= 5) and \
                    (len(good_title_card) <= 15 and len(description_card) <= 15):
                obj, created = Card.objects.get_or_create(title_card=good_title_card, board=unique_board,
                                                          defaults=
                                                          {'description_card': description_card})

                if created:
                    return HttpResponse(status=200)
                else:
                    return HttpResponse(status=406)
            else:
                return HttpResponse(status=409)
    else:
        return HttpResponse(status=400)


def delete_board(request, slug, board_id):
    """Delete board from boards list."""
    if request.method == 'DELETE':
        board = get_object_or_404(Board, slug=slug, pk=board_id)
        board.delete()
        return HttpResponse(status=200)
    else:
        return HttpResponse(status=409)


def delete_card(request, slug, card_id, board_id):
    """Delete card from specific board.
    Come back to specific board after deleting."""
    if request.method == "DELETE":
        card = Card.objects.get(pk=card_id)
        card.delete()
        return HttpResponseRedirect(reverse('board:board_detail', args=(slug, board_id)))
    else:
        return HttpResponse(status=409)


def success_button(request, slug, board_id, card_id):
    """Change card status to success status."""
    if request.method == 'POST':
        Card.objects.filter(pk=card_id).update(colors='card-success')
        return HttpResponse(status=200)
    else:
        return HttpResponse(status=409)


def warning_button(request, slug, board_id, card_id):
    """Change card status to warning status."""
    if request.method == 'POST':
        Card.objects.filter(pk=card_id).update(colors='card-warning')
        return HttpResponse(status=200)
    else:
        return HttpResponse(status=409)


def danger_button(request, slug, board_id, card_id):
    """Change card status to danger status."""
    if request.method == 'POST':
        Card.objects.filter(pk=card_id).update(colors='card-danger')
        return HttpResponse(status=200)
    else:
        return HttpResponse(status=409)

project/index/views.py
from django.shortcuts import render


def index(request):
    """Return index(home) page."""
    return render(request, "index/index.html")

project/board/templates/board/board.html
{% extends 'project/base.html' %}
{% load static %}
{% block styles %}<link rel="stylesheet" type="text/css" href="{% static 'board/cdn/vfg.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'board/style.css'%}" />{% endblock %}
{% block content %}
<!--tableWithRecords-->
<div id="tab" class="table table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th class="text-center">Title</th>
                <th class="text-center">Description</th>
                <th class="text-center">Category</th>
                <th class="text-center">Date</th>
                <th class="text-center">Time</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>{% for boards in board %}
            <tr>
                <td><a data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Create new card" class="new-tooltip" href="{{ boards.get_absolute_url }}">{{ boards.title }}</a>
                </td>
                <td>{{ boards.description }}</td>
                <td>{{ boards.category }}</td>
                <td>{{ boards.created_at}}</td>
                <td>{{ boards.created_at_time }}</td>
                <td class="catch">
                    <a data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Change order" class="new-tooltip"><img src="{% static '/board/images/list_png.png'%}" alt="list_icon">
                    </a>
                </td>
                <td>
                    <a id="delete" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Delete board" class="new-tooltip" href="{% url 'board:delete_board' slug=boards.slug board_id=boards.pk %}"><img src="{% static '/board/images/delete_png.png'%}" alt="delete_icon">
                    </a>
                </td>
            </tr>{% endfor %}
        </tbody>
    </table>
</div>
<p>Don't waste your time and ...</p>
<div id="button">
    <button class="button2" :class="{ 'active': active }" @click="clicked">
        <% active ? clickedText : buttonText %>
    </button>
</div>
<!--tableCreate-->
<div id="form" class="container py-5">
    <div class="panel panel-default">
        <div class="panel-heading">Create table:</div>
        <div class="panel-body">
            <form method="post">
                {% csrf_token %}
                <vue-form :state="formstate" v-model="formstate" v-on:submit.prevent="onSubmit">
                    <validate auto-label class="form-group required-field" :class="fieldClassName(formstate.title)">
                        <label>Title:</label>
                        <input type="title" name="title" class="form-control" required v-model.lazy="model.title" minlength="5" maxlength="15" id="title">
                        <field-messages name="title" show="$touched || $submitted" class="form-control-feedback">
                            <div>Success!</div>
                            <div slot="required">Title is a required field.</div>
                            <div slot="minlength">Enter least 5 characters.</div>
                        </field-messages>
                    </validate>
                    <validate auto-label class="form-group required-field" :class="fieldClassName(formstate.description)">
                        <label>Description:</label>
                        <input type="description" name="description" class="form-control" required v-model.lazy="model.description" minlength="5" maxlength="25" id="description">
                        <field-messages name="description" show="$touched || $submitted" class="form-control-feedback">
                            <div>Success!</div>
                            <div slot="required">Description is a required field.</div>
                            <div slot="minlength">Enter least 5 characters.</div>
                        </field-messages>
                    </validate>
                    <validate auto-label class="form-group required-field" :class="fieldClassName(formstate.category)">
                        <label>Category:</label>
                        <input type="category" name="category" class="form-control" required v-model.lazy="model.category" minlength="5" maxlength="25" id="category">
                        <field-messages name="category" show="$touched || $submitted" class="form-control-feedback">
                            <div>Success!</div>
                            <div slot="required">Category is a required field.</div>
                            <div slot="minlength">Enter least 5 characters.</div>
                        </field-messages>
                    </validate>
                    <div class="py-2 text-center">
                        <button type="submit" class="btn btn-primary" value="submit">Submit</button>
                    </div>
                </vue-form>
            </form>
        </div>
    </div>
</div>{% endblock %}
{% block scripts %}<script type="text/javascript" src="{% static 'board/cdn/vfg.js' %}"></script>
    <script type="text/javascript" src="{% static 'board/cdn/vue-form.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'board/form.js'%}"></script>
    <script type="text/javascript" src="{% static 'board/empty.js'%}"></script>
    <script type="text/javascript" src="{% static 'board/script.js'%}"></script>{% endblock %}

project/board/templates/board/board_detail.html
{% extends 'project/base.html' %}
{% load static %}
{% block styles %}<link rel="stylesheet" type="text/css" href="/static/board/cdn/vfg.css">
  <link rel="stylesheet" type="text/css" href="{% static 'board/style_card.css'%}" />{% endblock %}
{% block content %}
<p><a href="{% url 'board:list_of_board' %}" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Comeback to board list" class="new-tooltip">{{board.title}}</a></p>
<div class="flex-container">{% for i in board.card_set.all %}
    <div class="card {{i.colors}} flex-item">
        <ul class="nav nav-pills nav-fill">
            <li class="nav-item">
                <a data-toggle="tooltip" data-placement="top" title="" data-original-title="Change order" class="nav-link new-tooltip"><img class="move" src="{% static '/board/images/list_png.png'%}" alt="list_icon">
                </a>
            </li>
            <li class="nav-item">
                <a id="delete" href="{% url 'board:delete_card' board.slug board.pk i.id %}" data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete card" class="del nav-link new-tooltip"><img src="{% static '/board/images/delete_png.png'%}" alt="delete_icon">
                </a>
            </li>
        </ul>
        <h2>{{i.title_card}}</h2>
        <h3>{{i.description_card}}</h3>
        <div id="footer">
            <a class="pointer" data-toggle="collapse" data-target="#{{i.pk}}" aria-controls="{{i.pk}}">Change status</a>
            <div id="{{i.pk}}" class="collapse hide" aria-labelledby="headingOne">
                <div class="card-block">
                    <a id="success" href="{% url 'board:success_button' board.slug board.pk i.id %}">
                        <button type="button" class="btn btn-outline-success touch">Done!</button>
                    </a>
                    <a id="warning" href="{% url 'board:warning_button' board.slug board.pk i.id %}">
                        <button type="button" class="btn btn-outline-warning touch">In progress</button>
                    </a>
                    <a id="danger" href="{% url 'board:danger_button' board.slug board.pk i.id %}">
                        <button type="button" class="btn btn-outline-danger touch">Canceled</button>
                    </a>
                </div>
            </div>
        </div>
    </div>{% endfor %}
</div>
<div id="form" class="container py-5">
    <div class="panel panel-default">
        <div class="panel-heading">Create card:</div>
        <div class="panel-body">
            <form>
                {% csrf_token %}
                <vue-form :state="formstate" v-model="formstate" v-on:submit.prevent="onSubmit">
                    <validate auto-label class="form-group required-field" :class="fieldClassName(formstate.title_card)">
                        <label>Title:</label>
                        <input type="title_card" name="title_card" class="form-control" required v-model.lazy="model.title_card" minlength="5" maxlength="15" id="title_card">
                        <field-messages name="title_card" show="$touched || $submitted" class="form-control-feedback">
                            <div>Success!</div>
                            <div slot="required">Title is a required field.</div>
                            <div slot="minlength">Enter least 5 characters.</div>
                        </field-messages>
                    </validate>
                    <validate auto-label class="form-group required-field" :class="fieldClassName(formstate.description_card)">
                        <label>Description:</label>
                        <input type="description" name="description_card" class="form-control" required v-model.lazy="model.description_card" minlength="5" maxlength="15" id="description_card">
                        <field-messages name="description_card" show="$touched || $submitted" class="form-control-feedback">
                            <div>Success!</div>
                            <div slot="required">Description is a required field.</div>
                            <div slot="minlength">Enter least 5 characters.</div>
                        </field-messages>
                    </validate>
                    <div class="py-2 text-center">
                        <button type="submit" class="btn btn-primary" value="submit">Submit</button>
                    </div>
                </vue-form>
            </form>
        </div>
    </div>
</div>{% endblock %}
{% block scripts %}<script type="text/javascript" src="{% static 'board/cards.js'%}"></script>
    <script type="text/javascript" src="{% static 'board/cdn/vue-form.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'board/form_cards.js' %}"></script>{% endblock %}

project/index/templates/index/index.html
{% extends 'project/base.html' %}
{% load static %}
{% block styles %}<link rel="stylesheet" type="text/css" href="{% static 'index/style.css'%}" /> {% endblock %}
{% block content %}
<!--typer-->
<div class="app">
    <h1>Manage your time  <vue-typer
                        :text='["effectively.","wisely.","productively.","intelligently.","rationally.","well.","with Morello."]'
                        :repeat='0'
                        :shuffle='false'
                        initial-action='typing'
                        :pre-type-delay='80'
                        :type-delay='80'
                        :pre-erase-delay='1000'
                        :erase-delay='80'
                        erase-style='backspace'
                        :erase-on-complete='false'
                        caret-animation='blink'
                        ></vue-typer>
                </h1>
    <p>Let's start manage your time!</p>
    <a href="{% url 'board:list_of_board' %}">
        <button class="button3"><span>Continue</span>
        </button>
    </a>
    <p id="special">with love to</p>
    <a href="https://www.python.org/" target="_blank"><img class="img-fluid" draggable="false" src="{% static '/index/images/python_logo.svg' %}" alt="Python">
    </a>
</div>{% endblock %}
{% block scripts %}<script type="text/javascript" src="{% static 'index/cdn/vue-typer.min.js'%}"></script>
    <script type="text/javascript" src="{% static 'index/script.js'%}"></script>{% endblock %}

project/templates/project/base.html
<!DOCTYPE html>{% load static %}
<html lang="EN">
<head>
    <!--meta-->
    <meta charset="UTF-8">
    <meta name="author" content="Michał Janik">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="{% static '/index/images/apricot_icon.ico' %}" type="image/ico" />
    <title>Morello | Manage your time!</title>
    <!--styles-->
    <link rel="stylesheet" type='text/css' href='http://fonts.googleapis.com/css?family=Lato|Atma&subset=latin,latin-ext'>
    <link rel="stylesheet" href="{% static '/index/cdn/bootstrap.min.css'%}">
    {% block styles %}{% endblock %}
</head>
<!--navBar-->
<body id="body" ondragstart="return false" ondrop="return false">
  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'index'%}">
          <img draggable="false" src="{% static '/index/images/apricot_png.png' %}" width="30" height="30" class="d-inline-block align-top" alt="Morello"> Morello
      </a>
      <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
              <li class="nav-item active">
                  <a class="nav-link" href="{% url 'index'%}">Home</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" target="_blank" href="https://bitbucket.org/Greeny14/morello">About</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" target="_blank" href="https://www.linkedin.com/in/michal-janik">Contact</a>
              </li>
          </ul>
      </div>
  </nav>{% block content %}{% endblock %}
    <!--scripts-->
    <script type="text/javascript" src="{% static 'index/cdn/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'index/cdn/jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'board/cdn/jquery.cookie.min.js'%}"></script>
    <script type="text/javascript" src="{% static 'index/cdn/vue.min.js'%}"></script>
    <script type="text/javascript" src="{% static 'index/cdn/tether.min.js'%}"></script>
    <script type="text/javascript" src="{% static 'index/cdn/bootstrap.min.js'%}"></script>
    {% block scripts %}{% endblock %}
</body>
</html>